plugins {
    id 'net.fabricmc.fabric-loom' version '1.15.+'
    id 'maven-publish'
}

repositories {
    maven {
        url = "https://masa.dy.fi/maven/sakura-ryoko"
        content { includeGroupAndSubgroups("fi.dy.masa") }
    }
    maven {
        url = 'https://maven.fallenbreath.me/releases'
        content { includeGroupAndSubgroups("me.fallenbreath") }
    }
    maven {
        url = 'https://maven.terraformersmc.com/releases/'
        content { includeGroupAndSubgroups("com.terraformersmc") }
    }
    maven {
        url = 'https://jitpack.io'
        content { includeGroupAndSubgroups("com.github") }
    }
    flatDir {
        dir 'libs'
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
    implementation "com.google.code.findbugs:jsr305:3.0.2"

    // Локальные библиотеки из папки libs
    implementation files('libs/litematica-fabric-26.2-0.28.4.jar')
    implementation files('libs/malilib-fabric-26.2-0.29.3.jar')
    compileOnly files('libs/conditional-mixin-fabric-0.6.4.jar')
    compileOnly files('libs/modmenu-20.0.1.jar')

    api fabricApi.module("fabric-api-base", project.fabric_api_version)
}

base {
    group = project.maven_group + "." + project.mod_id
    archivesName = project.mod_file_name + '-' + project.minecraft_version_out
    version = project.mod_version

    if (version.endsWith('-dev')) {
        version += "." + new Date().format('yyyyMMdd.HHmmss')
    }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "litematica-printer" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

processResources {
    exclude '**/*.xcf'
    exclude '**/xcf'

    inputs.property "mod_version", project.mod_version

    filesMatching("fabric.mod.json") {
        expand "mod_version": project.mod_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 25
}

tasks.withType(AbstractArchiveTask).configureEach {
    preserveFileTimestamps = true
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${base.archivesName.get()}"}
    }
}

tasks.publish.dependsOn build
publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            from components.java
        }
    }

    repositories {
        maven {
            url = "$projectDir/../../CommonMaven"
        }
    }
}