plugins {
    id 'fabric-loom' version '1.15-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://jitpack.io" }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.mappings_version}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // ПОДКЛЮЧЕНИЕ ЛОКАЛЬНЫХ ФАЙЛОВ
    modImplementation files("libs/litematica-fabric-1.21.11-0.26.2.jar")
    modImplementation files("libs/malilib-fabric-1.21.11-0.27.7.jar")
    modImplementation files("libs/conditional-mixin-fabric-0.6.4.jar")

    implementation "com.google.code.findbugs:jsr305:3.0.2"
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "modid" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

processResources {
    inputs.property "version", project.version
    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    inputs.property "archivesName", project.base.archivesName
    from("LICENSE") {
        rename { "${it}_${inputs.properties.archivesName}"}
    }
}

// Ремаппинг вложенных зависимостей (важно для принтера)
tasks.withType(net.fabricmc.loom.task.RemapJarTask).configureEach {
    addNestedDependencies = true
}