org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Параметры Minecraft 1.21.11
minecraft_version=1.21.11
mappings_version=1.21.11+build.4
loader_version=0.18.2
fabric_version=0.139.4+1.21.11
loom_version=1.15-SNAPSHOT

# Свойства мода
mod_version=5.3.0
maven_group=com.example
archives_base_name=litematica-printer-fast-place