org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Параметры Minecraft 26.2
minecraft_version=26.2
minecraft_version_out=26.2
loader_version=0.19.3
fabric_version=0.152.1+26.2
loom_version=1.15-SNAPSHOT

# Mappings (Mojang - без yarn_mappings)
minecraft_version_type=release

# Свойства мода
mod_version=6.0.0
maven_group=io.github.sakura-ryoko
archives_base_name=litematica-printer

# Dependencies - обновлено для совместимости с litematica 0.28.4 и malilib 0.29.3
litematica_version=0.28.4
malilib_version=0.29.3